# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # On schedule
  schedule:
    - cron: "0 2 * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: update package
        run: |
          sudo apt update -y
          # sudo apt full-upgrade -y
      - name: install requirement
        run: |
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
          git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
          mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools \
          libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip \
          vim wget xmlto xxd zlib1g-dev python3-setuptools jq
      - name: fetch lede source code
        run: |
          working_path=$(pwd)
          git clone https://github.com/coolsnowwolf/lede
          cd ${working_path}/lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: fetch package source code
        run: |
          working_path=$(pwd)
          cd ${working_path}/lede/package
          git clone https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic.git
      - name: configure
        run: |
          working_path=$(pwd)
          curl -C - --retry 5 -o ${working_path}/lede/.config https://raw.githubusercontent.com/sht2017/lede-86_64-luci-app-unblockneteasemusic/main/main.config
          yes "" | make oldconfig
      - name: patch config
        run: |
          sed -i 's/# CONFIG_PACKAGE_node is not set/CONFIG_PACKAGE_node=y/g' .config
          sed -i 's/CONFIG_NODEJS_16=y/# CONFIG_NODEJS_16 is not set/g' .config
          sed -i 's/# CONFIG_NODEJS_18 is not set/CONFIG_NODEJS_18=y\n# CONFIG_NODEJS_ICU_NONE is not set\n# CONFIG_NODEJS_ICU_SMALL is not set\nCONFIG_NODEJS_ICU_SYSTEM=y/g' .config
          sed -i 's/# CONFIG_PACKAGE_icu is not set/CONFIG_PACKAGE_icu=y/g' .config
          sed -i 's/# CONFIG_PACKAGE_icu-full-data is not set/CONFIG_PACKAGE_icu-full-data=y/g' .config
          sed -i 's/# CONFIG_PACKAGE_libcares is not set/CONFIG_PACKAGE_libcares=y/g' .config
          sed -i 's/# CONFIG_PACKAGE_luci-app-unblockneteasemusic is not set/CONFIG_PACKAGE_luci-app-unblockneteasemusic=y/g' .config
      - name: get toolchain
        run: |
          working_path=$(pwd)
          version=$(curl -s "https://api.github.com/repos/openwrt/openwrt/tags" | jq -r '.[0] | .name' | tr -d v)
          url=https://downloads.openwrt.org/releases/${version}/targets/x86/64/
          sdk_url=${url}$(curl -s ${url} | grep sdk | sed -n 's/.*href="\([^"]*\)".*/\1/p; q')
          curl -C - --retry 5 -o /tmp/openwrt_sdk.xz ${sdk_url}
          mkdir ${working_path}/sdk
          tar -Jxvf /tmp/openwrt_sdk.xz --strip-components=1 -C ${working_path}/sdk --wildcards */staging_dir/
          toolchain=$(ls ${working_path}/lede/staging_dir | grep toolchain)
          rm -rf ${working_path}/lede/staging_dir/${toolchain}
          ln -s ${working_path}/sdk/staging_dir/$(ls ${working_path}/sdk/staging_dir/ | grep toolchain) ${working_path}/lede/staging_dir/${toolchain}
      - name: compile
        run: |
          working_path=$(pwd)
          cd ${working_path}/lede
          make download -j8
          make V=s -j1
      
    
